name: Testing, building and push to ACR

# trigger for this pipeline whe code  push to a testing branch
on:
  push:
    branches: [ testing ]

permissions:
  contents: read
  id-token: write   # Required for OIDC

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

# Define global environment variables that can be used across jobs
env:
  # Dynamically generate image tags based on Git SHA and GitHub Run ID
  # This provides unique, traceable tags for each image build
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  RG_STAGING: anusha-rg-stg
  AKS_STAGING: anusha-aks-stg
  NS: staging

jobs:
  # Job 1: Run tests and linting for all backend services
  test_and_lint_services:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    services:
      # Product DB container
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        # Make pg_isready available so the service is healthy before tests run
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Customer DB
      customer_db:
          image: postgres:15
          env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: customers
          ports:
              - 5434:5432
          options: >-
              --health-cmd "pg_isready -U postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    steps:
      # 1. Checkout the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      # 2. Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5 # Action to set up Python environment
        with:
          python-version: '3.10'

      # 3. Install dependencies and run code quality checks
      - name: Install dependencies
        run: | # Use a multi-line script to install pip dependencies
          cd k8s/
          ls 
          cd ..
          pip install --upgrade pip
          # Loop through each backend service folder
          for req in backend/*/requirements.txt; do
            echo "Installing $req"
            pip install -r "$req"
          done
          # Install CI tools
          pip install pytest httpx


      # 5. Run tests for product service

      - name: Run product_service tests
        working-directory: backend/product_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_DB: products
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q

      - name: Run order_service tests
        working-directory: backend/order_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_DB: orders
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q


      - name: Run customer_service tests
        working-directory: backend/customer_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5434
            POSTGRES_DB: customers
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q


  # Job 2: Build and Push Docker Images (runs only if tests pass and image_push is true)
  build_and_push_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    needs: [test_and_lint_services]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login using a Service Principal secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

      # Build and Push Docker image for Product Service
      - name: Build and Push Product Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest

      # Build and Push Docker image for Order Service
      - name: Build and Push Order Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest ./backend/order_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest

      # Build and Push Docker image for Customer Service
      - name: Build and Push Customer Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest ./backend/customer_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest

      # Build and Push Docker image for Frontend Service
      - name: Build and Push Frontend Image
        run: |
          docker build -t "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest" ./frontend/
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"
      
      - name: Logout from Azure
        run: az logout

 # Job 1: Deploy to Production
  deploy_to_production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      RG_PRODUCTION: anusha-rg-prod
      AKS_PRODUCTION: anusha-aks-prod
      NS: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          set -euo pipefail
          az aks get-credentials --resource-group "$RG_PRODUCTION" --name "$AKS_PRODUCTION" --overwrite-existing

      - name: Create namespace & set context
        run: |
          set -euo pipefail
          kubectl create namespace "$NS" --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl config set-context --current --namespace="$NS"
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Current context: $CURRENT_CONTEXT"

      - name: Apply backend config & databases
        run: |
          set -euo pipefail
          kubectl apply -n "$NS" -f k8s/configmaps.yaml
          kubectl apply -n "$NS" -f k8s/secrets.yaml
          kubectl apply -n "$NS" -f k8s/product-db.yaml
          kubectl apply -n "$NS" -f k8s/order-db.yaml

      - name: Deploy Product & Order services
        run: |
          set -euo pipefail
          kubectl apply -n "$NS" -f k8s/product-service.yaml
          kubectl apply -n "$NS" -f k8s/order-service.yaml
          kubectl get all -n "$NS"

      - name: Deploy Backend Infrastructure (Namespace, ConfigMaps, Secrets, Databases)
        run: |
          set -euo pipefail
          echo "Deploying backend infrastructure..."
          cd k8s/
          kubectl apply -n "$NS" -f configmaps.yaml
          kubectl apply -n "$NS" -f secrets.yaml
          kubectl apply -n "$NS" -f product-db.yaml
          kubectl apply -n "$NS" -f customer-db.yaml
          kubectl apply -n "$NS" -f order-db.yaml

      - name: Deploy Backend Microservices (Product, Customer, Order)
        run: |
          set -euo pipefail
          echo "Deploying backend microservices..."
          cd k8s/
          kubectl apply -n "$NS" -f product-service.yaml
          kubectl apply -n "$NS" -f customer-service.yaml
          kubectl apply -n "$NS" -f order-service.yaml
      
      - name: Wait for Backend LoadBalancer IPs
        env:
          PRODUCT_SERVICE_NAME:  "product-service-w08e1"
          CUSTOMER_SERVICE_NAME: "customer-service-w08e1"
          ORDER_SERVICE_NAME: "order-service-w08e1"

        run: |
          set -euo pipefail
          echo "Waiting for Product, Customer, Order LoadBalancer IPs to be assigned (up to 5 minutes)..."
          PRODUCT_IP=""
          CUSTOMER_IP=""
          ORDER_IP=""
          
          for i in $(seq 1 60); do
            echo "Attempt $i/60 to get IPs..."
            PRODUCT_IP=$(kubectl get service "$PRODUCT_SERVICE_NAME" -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            CUSTOMER_IP=$(kubectl get service "$CUSTOMER_SERVICE_NAME" -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            ORDER_IP=$(kubectl get service "$ORDER_SERVICE_NAME" -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

            if [[ -n "$PRODUCT_IP" && -n "$CUSTOMER_IP" && -n "$ORDER_IP" ]]; then
              echo "All backend LoadBalancer IPs assigned!"
              echo "Product Service IP: $PRODUCT_IP"
              echo "Customer Service IP: $CUSTOMER_IP"
              echo "Order Service IP: $ORDER_IP"
              break
            fi
            sleep 5 # Wait 5 seconds before next attempt
          done
          
          if [[ -z "$PRODUCT_IP"|| -z "$CUSTOMER_IP" || -z "$ORDER_IP" ]]; then
            echo "Error: One or more LoadBalancer IPs not assigned after timeout."
            exit 1 # Fail the job if IPs are not obtained
          fi
          
          # These are environment variables for subsequent steps in the *same job*
          # And used to set the job outputs
          echo "PRODUCT_IP=$PRODUCT_IP" >> $GITHUB_ENV
          echo "CUSTOMER_IP=$CUSTOMER_IP" >> $GITHUB_ENV
          echo "ORDER_IP=$ORDER_IP" >> $GITHUB_ENV

          echo " Deployed to production environment successfully!"

      - name: Capture Product Service IP for Workflow Output
        id: get_product_ip
        run: echo "external_ip=${{ env.PRODUCT_IP }}" >> $GITHUB_OUTPUT

      - name: Capture Order Service IP for Workflow Output
        id: get_order_ip
        run: echo "external_ip=${{ env.ORDER_IP }}" >> $GITHUB_OUTPUT

      - name: Capture Customer Service IP for Workflow Output
        id: get_customer_ip
        run: echo "external_ip=${{ env.CUSTOMER_IP }}" >> $GITHUB_OUTPUT

      - name: Inject Backend IPs into Frontend main.js
        run: |
          echo "Injecting IPs into frontend/static/js/main.js"

          PRODUCT_IP=${{ steps.get_product_ip.outputs.external_ip }}
          ORDER_IP=${{ steps.get_order_ip.outputs.external_ip }}
          CUSTOMER_IP=${{ steps.get_customer_ip.outputs.external_ip }}

          # Ensure frontend/main.js is directly in the path for sed
          sed -i "s|_PRODUCT_API_URL_|http://$PRODUCT_IP:8000|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|http://$ORDER_IP:8001|g" frontend/main.js
          sed -i "s|_CUSTOMER_API_URL_|http://$CUSTOMER_IP:8002|g" frontend/main.js
          
          # Display the modified file content for debugging
          echo "--- Modified main.js content ---"
          cat frontend/main.js
          echo "---------------------------------"
      
      # Build and Push Docker image for Frontend
      - name: Build and Push Frontend Image
        run: |
          set -euo pipefail
          docker build -t "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest" ./frontend/
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"

      - name: Deploy Frontend to AKS
        run: |
          set -euo pipefail

          echo "Deploying frontend to AKS cluster.."
          
          cd k8s/
          # Ensure frontend-service.yaml is configured with your ACR
          kubectl apply -n "$NS" -f frontend.yaml
            - name: Deploy Production Application
        run: |
          echo " Deploying to production environment..."
          kubectl apply -f k8s/
          echo " Waiting for services to initialize..."
          sleep 120

      - name: Wait for Frontend LoadBalancer IPs
        env:
          FRONTEND_SERVICE_NAME: "frontend-w08e1"
        run: |
          set -euo pipefail
          echo "Waiting for Frontend LoadBalancer IPs to be assigned (up to 5 minutes)..."
          FRONTEND_IP=""
          
          for i in $(seq 1 60); do
            echo "Attempt $i/60 to get IP..."
            FRONTEND_IP=$(kubectl get service "$FRONTEND_SERVICE_NAME" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

            if [[ -n "$FRONTEND_IP" ]]; then
              echo "Frontend LoadBalancer IPs assigned: $FRONTEND_IP"
              break
            fi
            sleep 5 # Wait 5 seconds before next attempt
          done
          
          if [[ -z "$FRONTEND_IP" ]]; then
            echo "Error: One or more LoadBalancer IPs not assigned after timeout."
            exit 1 # Fail the job if IP is not obtained
          fi
          
          # These are environment variables for subsequent steps in the *same job*
          # And used to set the job outputs
          echo "FRONTEND_IP=$FRONTEND_IP" >> $GITHUB_ENV

      - name: Capture Frontend Service IP for Workflow Output
        id: get_frontend_ip
        run: echo "external_ip=${{ env.FRONTEND_IP }}" >> $GITHUB_OUTPUT

      - name: Logout from Azure
        run: az logout