name: Testing, building and push to ACR and Deploy to Staging

# trigger for this pipeline whe code  push to a testing branch
on:
  push:
    branches: [ testing ]

permissions:
  contents: read
  id-token: write   # Required for OIDC

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

# Define global environment variables that can be used across jobs
env:
  # Dynamically generate image tags based on Git SHA and GitHub Run ID
  # This provides unique, traceable tags for each image build
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  RG_STAGING: "anusha-rg-stg"
  AKS_STAGING: "anusha-aks-stg"
  NS: "staging"

jobs:
  # Job 1: Run tests and linting for all backend services
  test_and_lint_services:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    services:
      # Product DB container
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        # Make pg_isready available so the service is healthy before tests run
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Customer DB
      customer_db:
          image: postgres:15
          env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: customers
          ports:
              - 5434:5432
          options: >-
              --health-cmd "pg_isready -U postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    steps:
      # 1. Checkout the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      # 2. Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5 # Action to set up Python environment
        with:
          python-version: '3.10'

      # 3. Install dependencies and run code quality checks
      - name: Install dependencies
        run: | # Use a multi-line script to install pip dependencies
          cd k8s/
          ls 
          cd ..
          pip install --upgrade pip
          # Loop through each backend service folder
          for req in backend/*/requirements.txt; do
            echo "Installing $req"
            pip install -r "$req"
          done
          # Install CI tools
          pip install pytest httpx


      # 5. Run tests for product service

      - name: Run product_service tests
        working-directory: backend/product_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_DB: products
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q

      - name: Run order_service tests
        working-directory: backend/order_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_DB: orders
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q


      - name: Run customer_service tests
        working-directory: backend/customer_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5434
            POSTGRES_DB: customers
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q


  # Job 2: Build and Push Docker Images (runs only if tests pass and image_push is true)
  build_and_push_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    needs: [test_and_lint_services]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login using a Service Principal secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

      # Build and Push Docker image for Product Service
      - name: Build and Push Product Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest

      # Build and Push Docker image for Order Service
      - name: Build and Push Order Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest ./backend/order_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest

      # Build and Push Docker image for Customer Service
      - name: Build and Push Customer Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest ./backend/customer_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest

      # Build and Push Docker image for Frontend Service
      - name: Build and Push Frontend Image
        run: |
          docker build -t "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest" ./frontend/
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"
      
      - name: Logout from Azure
        run: az logout
# STAGE 3: Deploy to Staging Environment
  deploy-staging:
    name: Deploy to Staging
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo files for debug
        run: ls -la

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          set -euo pipefail
          az aks get-credentials --resource-group "${{ env.RG_STAGING }}" --name "${{ env.AKS_STAGING }}" --overwrite-existing

      - name: Create staging namespace
        run: kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to staging namespace
        run: |
          echo "Deploying to staging environment..."
          kubectl apply -f temp-k8s/ -n staging
          echo " Waiting for services to be ready..."
          sleep 30
          kubectl get deployments -n staging
          kubectl get pods -n staging
          echo " Staging deployment completed!"

  # STAGE 4: Destroy Staging Environment
  destroy-staging:
    name: Destroy Staging
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          set -euo pipefail
          az aks get-credentials --resource-group "${{ env.RG_STAGING }}" --name "${{ env.AKS_STAGING }}" --overwrite-existing
      
      - name: Recreate temp-k8s for cleanup
        run: cp -r k8s/ temp-k8s/

      - name: Destroy staging environment
        run: |
          echo "Destroying staging environment..."
          kubectl delete -f temp-k8s/ -n staging --ignore-not-found=true
          kubectl delete namespace staging --ignore-not-found=true
          echo "Staging environment destroyed!"