name: Testing, building and push to ACR and Deploy to Staging

# trigger for this pipeline whe code  push to a testing branch
on:
  push:
    branches: [ testing ]

permissions:
  contents: read
  id-token: write   # Required for OIDC

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

# Define global environment variables that can be used across jobs
env:
  # Dynamically generate image tags based on Git SHA and GitHub Run ID
  # This provides unique, traceable tags for each image build
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  RG_STAGING: "anusha-rg-stg"
  AKS_STAGING: "anusha-aks-stg"
  NS: "staging"

jobs:
  # Job 1: Run tests and linting for all backend services
  test_and_lint_services:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    services:
      # Product DB container
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        # Make pg_isready available so the service is healthy before tests run
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Customer DB
      customer_db:
          image: postgres:15
          env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: customers
          ports:
              - 5434:5432
          options: >-
              --health-cmd "pg_isready -U postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    steps:
      # 1. Checkout the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      # 2. Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5 # Action to set up Python environment
        with:
          python-version: '3.10'

      # 3. Install dependencies and run code quality checks
      - name: Install dependencies
        run: | # Use a multi-line script to install pip dependencies
          cd k8s/
          ls 
          cd ..
          pip install --upgrade pip
          # Loop through each backend service folder
          for req in backend/*/requirements.txt; do
            echo "Installing $req"
            pip install -r "$req"
          done
          # Install CI tools
          pip install pytest httpx


      # 5. Run tests for product service

      - name: Run product_service tests
        working-directory: backend/product_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_DB: products
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q

      - name: Run order_service tests
        working-directory: backend/order_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_DB: orders
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q


      - name: Run customer_service tests
        working-directory: backend/customer_service
        env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5434
            POSTGRES_DB: customers
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
            pytest tests --maxfail=1 --disable-warnings -q


  # Job 2: Build and Push Docker Images (runs only if tests pass and image_push is true)
  build_and_push_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    needs: [test_and_lint_services]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login using a Service Principal secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

      # Build and Push Docker image for Product Service
      - name: Build and Push Product Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest

      # Build and Push Docker image for Order Service
      - name: Build and Push Order Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest ./backend/order_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest

      # Build and Push Docker image for Customer Service
      - name: Build and Push Customer Service Image
        run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest ./backend/customer_service/
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest

      # Build and Push Docker image for Frontend Service
      - name: Build and Push Frontend Image
        run: |
          docker build -t "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest" ./frontend/
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"
      
      - name: Logout from Azure
        run: az logout

 #  Deploy to staging
  deploy_to_staging:
    runs-on: ubuntu-latest
    needs: [build_and_push_images]
    if: always() && needs.build_and_push_images.result == 'success'
    env:
      NS: "staging"
      PRODUCT_SERVICE_NAME:  "product-service-w10-aks"
      CUSTOMER_SERVICE_NAME: "customer-service-w10-aks"
      ORDER_SERVICE_NAME: "order-service-w10-aks"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Display Trigger Information
        run: |
          echo "Staging Resource Group: ${{ env.RG_STAGING }}"
          echo "Staging AKS Cluster: ${{ env.AKS_STAGING }}"

      - name: Get AKS credentials
        run: |
          set -euo pipefail
          az aks get-credentials --resource-group "${{ env.RG_STAGING }}" --name "${{ env.AKS_STAGING }}" --overwrite-existing

      - name: Create staging namespace
        run: kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Backend Infrastructure (Namespace, ConfigMaps, Secrets, Databases)
        run: |
          set -euo pipefail
          echo "Deploying backend infrastructure..."
          cd k8s/
          kubectl apply -f configmaps.yaml -n staging
          kubectl apply -f secrets.yaml -n staging
          kubectl apply -f product-db.yaml -n staging
          kubectl apply -f order-db.yaml -n staging
          kubectl apply -f customer-db.yaml -n staging

      - name: Deploy Product & Order services
        run: |
          set -euo pipefail
          cd k8s/
          kubectl apply -f product-service.yaml -n staging
          kubectl apply -f order-service.yaml -n staging
          kubectl apply -f customer-service.yaml -n staging
      

      - name: Get Staging Environment URLs
        run: |
          PRODUCT_IP=""
          ORDER_IP=""
          CUSTOMER_IP=""
          
          for i in $(seq 1 60); do
            echo "Attempt $i/60 to get IPs..."
            PRODUCT_IP=$(kubectl get service "$PRODUCT_SERVICE_NAME" -n staging -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            ORDER_IP=$(kubectl get service "$ORDER_SERVICE_NAME" -n staging -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            CUSTOMER_IP=$(kubectl get svc "$CUSTOMER_SERVICE_NAME" -n staging -o jsonpath="{.status.loadBalancer.ingress[0].ip}")

            if [[ -n "$PRODUCT_IP" && -n "$ORDER_IP" || -z "$CUSTOMER_IP" ]]; then
              echo "All backend LoadBalancer IPs assigned!"
              echo "Product Service IP: $PRODUCT_IP"
              echo "Order Service IP: $ORDER_IP"
              echo "Order Service IP: $CUSTOMER_IP"
              break
            fi
            sleep 30 # Wait 5 seconds before next attempt
          done
          

          # Ensure frontend/main.js is directly in the path for sed
          sed -i "s|_PRODUCT_API_URL_|http://$PRODUCT_IP:8000|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|http://$ORDER_IP:8001|g" frontend/main.js
          sed -i "s|_CUSTOMER_API_URL_|http://$CUSTOMER_IP:8002|g" frontend/main.js
          
          # Display the modified file content for debugging
          echo "--- Modified main.js content ---"
          cat frontend/main.js
          echo "---------------------------------"


      
      # Build and Push Docker image for Frontend
      - name: Build and Push Frontend Image
        run: |
          set -euo pipefail
          docker build -t "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest" ./frontend/
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"

      - name: Deploy Frontend to AKS
        run: |
          set -euo pipefail

          echo "Deploying frontend to AKS cluster.."
          
          cd k8s/
          # Ensure frontend.yaml is configured with your ACR
          kubectl apply -f frontend.yaml -n staging

      - name: Wait for Frontend LoadBalancer IPs
        env:
          FRONTEND_SERVICE_NAME: "frontend-w10-aks"
        run: |
          set -euo pipefail
          
          echo "Waiting for Frontend LoadBalancer IPs to be assigned (up to 5 minutes)..."
          FRONTEND_IP=""
          
          for i in $(seq 1 60); do
            echo "Attempt $i/60 to get IP..."
            FRONTEND_IP=$(kubectl get service "$FRONTEND_SERVICE_NAME" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

            if [[ -n "$FRONTEND_IP" ]]; then
              echo "Frontend LoadBalancer IPs assigned: $FRONTEND_IP"
              break
            fi
            sleep 30 # Wait 5 seconds before next attempt
          done
          
          if [[ -z "$FRONTEND_IP" ]]; then
            echo "Error: One or more LoadBalancer IPs not assigned after timeout."
            exit 1 # Fail the job if IP is not obtained
          fi
          
          # These are environment variables for subsequent steps in the *same job*
          # And used to set the job outputs
          echo "FRONTEND_IP=$FRONTEND_IP" >> $GITHUB_ENV

          echo " STAGING ENVIRONMENT DEPLOYED SUCCESSFULLY!"
 
      - name: Logout from Azure
        run: az logout
        if: always()

      - name: Logout from Azure
        run: az logout

  # Job 5: Destroy Staging Environment
  destroy_staging_environment:
    runs-on: ubuntu-latest
    needs: [deploy_to_staging]
    if: always() && needs.deploy_to_staging.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RG_STAGING }} \
            --name ${{ env.AKS_STAGING }} \
            --overwrite-existing
          
          kubectl get svc -n staging
      - name: Wait for manual testing
        run: |
          echo " Pausing for manual testing (1 minutes)..."
          sleep 60 # Sleep for 1 minutes to allow manual testing

      - name: Delete Backend Infrastructure (Namespace, ConfigMaps, Secrets, Databases)
        run: |
          echo "Deleting backend infrastructure..."
          cd k8s/
          kubectl delete -f configmaps.yaml -n staging
          kubectl delete -f secrets.yaml -n staging
          kubectl delete -f product-db.yaml -n staging
          kubectl delete -f order-db.yaml -n staging
          kubectl delete -f customer-db.yaml -n staging
      

      - name: Delete Backend Microservices (Product, Order)
        run: |
          echo "Deleting backend microservices..."
          cd k8s/
          kubectl delete -f product-service.yaml -n staging
          kubectl delete -f order-service.yaml -n staging
          kubectl delete -f customer-service.yaml -n staging

      - name: Logout from Azure
        run: az logout
        if: always() 

  