name: Testing, building and push to ACR - Stage1
# trigger for this pipeline whe code  push to a testing branch
on:
  push:
    branches: [ testing ]

permissions:
  contents: read
  id-token: write   # Required for OIDC

concurrency:
  group: stage1-${{ github.ref }}
  cancel-in-progress: true

# Define global environment variables that can be used across jobs
env:
  # Dynamically generate image tags based on Git SHA and GitHub Run ID
  # This provides unique, traceable tags for each image build
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  # Job 1: Run tests and linting for all backend services
  test_and_lint_services:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner
    strategy:
      matrix:
        service: [product_service, order_service, customer_service]
    services:
      # Product DB container
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        # Make pg_isready available so the service is healthy before tests run
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Customer DB
      customer_db:
          image: postgres:15
          env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: customers
          ports:
              - 5434:5432
          options: >-
              --health-cmd "pg_isready -U postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    steps:
      # 1. Checkout the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 2. Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5 # Action to set up Python environment
        with:
          python-version: '3.10'

      # 3. Install dependencies and run code quality checks
      - name: Install dependencies
        run: | # Use a multi-line script to install pip dependencies
          cd k8s/
          ls 
          cd ..
          pip install --upgrade pip
          # Loop through each backend service folder
          for req in backend/*/requirements.txt; do
            echo "Installing $req"
            pip install -r "$req"
          done
          # Install CI tools
          pip install pytest httpx

      # 5. Run tests for backend service
      - name: Run tests for ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ matrix.service == 'product_service' && '5432' || (matrix.service == 'order_service' && '5433' || '5434') }}
          POSTGRES_DB: ${{ matrix.service == 'product_service' && 'products' || (matrix.service == 'order_service' && 'orders' || 'customers') }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          pytest tests --maxfail=1 --disable-warnings -q


  # Job 2: Build and Push Docker Images (runs only if tests pass and image_push is true)
  build_and_push_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product_service, order_service, customer_service, frontend]
    needs: [test_and_lint_services]
    if: always() && needs.test_and_lint_services.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login using a Service Principal secret
      - name: Azure Login 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
        

      # Build and Push Docker image for Backend Services
      - name: Build & Push ${{ matrix.service }} image
        run: |
          docker build  -f backend/${{ matrix.service }}/Dockerfile -t "${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest" backend/${{ matrix.service }}
          docker tag  "${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}" "${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest"
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}"
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest"

      # Build and Push Docker image for Frontend
      - name: Build and Push Frontend Image
        run: |
          docker build -f frontend/Dockerfile -t "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest" frontend
          docker tag  "${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}" "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}"
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest"
      
      - name: Logout from Azure
        run: az logout